const indexPage = require('./indexPage')

const createSectors = require('./createSectors')
const sectors = require('./sectors')
const createStocksInSectors = require('./createStocksInSectors')
const stocksInSectors = require('./stocksInSectors')
const createIndexes = require('./createIndexes')
const indexes = require('./indexes')
const createStocksInIndexes = require('./createStocksInIndexes')
const stocksInIndexes = require('./stocksInIndexes')
const createStocks = require('./createStocks')
const stocks = require('./stocks')
const balanceSheets = require('./balancesheets')
const balanceSheetDates = require('./balancesheetdates')

const stockMarketApi = require("./api/stockmarket")
const balanceSheetDatesApi = require("./api/balancesheetdates")
const sectorsApi = require('./api/sectors')
const stocksInSectorsApi = require('./api/stocksInSectors')
const indexesApi = require("./api/indexes")
const stocksInIndexesApi = require("./api/stocksInIndexes")
const stocksApi = require("./api/stocks")
const balanceSheetsApi = require("./api/balancesheets")

module.exports = function (app) {
    app.use("/", indexPage)

    app.use("/createSectors", createSectors)
    app.use("/sectors", sectors)
    app.use("/createStocksInSectors", createStocksInSectors)
    app.use("/stocksInSectors", stocksInSectors)
    app.use("/createIndexes", createIndexes)
    app.use("/createStocksInIndexes", createStocksInIndexes)
    app.use("/indexes", indexes)
    app.use("/stocksInIndexes", stocksInIndexes)
    app.use("/createStocks", createStocks)
    app.use("/stocks", stocks)
    app.use("/balanceSheets", balanceSheets)
    app.use("/balanceSheetDates", balanceSheetDates)

    app.use("/api/stockMarket", stockMarketApi)
    app.use("/api/balancesheetdates", balanceSheetDatesApi)
    app.use("/api/sectors", sectorsApi)
    app.use("/api/stocksInSectors", stocksInSectorsApi)
    app.use("/api/indexes", indexesApi)
    app.use("/api/stocksInIndexes", stocksInIndexesApi)
    app.use("/api/stocks", stocksApi)
    app.use("/api/balanceSheets", balanceSheetsApi)
}